branch-defaults:
  default:
    environment: Upforweb-env
    group_suffix: null
  master:
    environment: Upforweb-env
global:
  application_name: upforweb
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
